### ISSUE TITLE
unable to install jsdoc-to-markdown due to github dependency for taffydb

### ISSUE THREAD

**Issue by mbayfield** [jsdoc2md/jsdoc#2]
In the very rare instance when Github was offline last week, "npm install" failed to install jsdoc-to-markdown due to the taffydb dependency in this module that links directly to Github. 

Is there a reason this module doesn't use an npm version of taffydb?
https://www.npmjs.com/package/taffydb

Could it be linked to the npm module version?

**Comment by 75lb** [comment]
good point.. [issue raised](https://github.com/jsdoc3/jsdoc/issues/1153)

**Comment by mbayfield** [comment]
Thank you

**Comment by 75lb** [comment]
rather than wait for jsdoc3 i released my own 'taffydb-75lb' module to fix the issue in this fork.. released in jsdoc-75lb v3.5.4.
